<?php
/**
 * @file
 * A block module to pull all of a users soundcloud uploads and display them.
 */

/**
 * Set the artist_id, 
 * change this to be the id of the artist you want to pull from.
 *
 */
function get_artist_id(){
	$artist_id = '604703';
	return $artist_id;
}

/**
 * Implements hook_help
 * Displays help and module information.
 * @param path
 *	Which path of the site we're using to display help
 * @ param arg
 *	Array that holds the current path as returned from the arg() functino
 */
 function soundcloud_grab_help($path, $arg){
 	switch($path){
 	case "admin/help#soundcloud_grab":
 		return '<p>' . t("displays soundcloud uploads") . '</p>';
 		break;
 	}
 }

/**
 * Implements hook_block_info().
 */
function soundcloud_grab_block_info() {
	$blocks['soundcloud_grab'] = array(
		// The name that will appear in the block list.
		'info' => t('Soundcloud Grab'),
		// Default setting.
		'cache' => DRUPAL_CACHE_PER_ROLE,
	);
	return $blocks;
}

/**
 * Custom Content Function.
 *
 * Run a curl to the soundcloud api to get the URLs
 * of a users uploads.
 *
 * @return
 *	A json of sound cloud upload infos...
 */
function soundcloud_grab_contents($url){
	$ch = curl_init();
	$timeout = 5;
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
	$data = curl_exec($ch);
	curl_close($ch);
	$data = json_decode($data, true);
	$embed_code = '';
	foreach ($data as $track){
		// $embed_code .= "<br>" . $track['id'] . "<br>HIT";
		$embed_code .= '<br><iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/' . $track["id"] . '&amp;auto_play=false&amp;hide_related=false&amp;visual=true"></iframe><br>';
	}
	return $embed_code;
}

function soundcloud_grab_block_view($delta = ''){
	switch ($delta) {
		case 'soundcloud_grab':
			//$block['subject'] = t('Dj Mixes');
			if (user_access('access content')){
				//get the artists id
				$artist_id = get_artist_id();
				//retrieve data
				$block['content'] = soundcloud_grab_contents('http://api.soundcloud.com/users/' . $artist_id . '/tracks.json?client_id=YOUR_CLIENT_ID');
				return $block;
			}
	}
}